version: '3'

services:
  nodejs:
    build: .
    image: renodocker/nodejs:latest-lts
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 8080:8080
    command: "npm run dev-docker"